### ISSUE TITLE
Trust mechanic is broken

### ISSUE THREAD

**Issue by z-em1** [Factorio-Biter-Battles/Factorio-Biter-Battles#213]
Untrusted are allowed to put bp down, with copy paste. It create bugs as they can put bp but not red cross from deconstruct planer, and so overlaping ghost over existing buildings, which lead to desync loop hell. Malicious people have found that so it's a high prioirty fixe needed. It seems to be pretty recent.

**Comment by Tomab** [comment]
There is more going on here.  Removing only the game.tick check will lead to potentially more desync scenarios.  I recommend simplifying the code so that only trusted players can place ghosts/blueprints and only trusted players can use the deconstruction planner so as to reduce the number of scenarios where desyncs can occur.  Please let me know if I can be of any more assistance on this issue (I've closed my pull request).

**Comment by Ragnarok77-factorio** [comment]
No more issue about that, closing it
